name: Test


on:
  push:
  workflow_dispatch:

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - run: id
      - run: umask
      
  test-container:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - run: id
      - run: umask
