name: Test


on:
  #push:
  workflow_dispatch:

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - run: id
      - run: umask
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-container:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - run: id
      - run: umask
